#!/bin/sh

case "$1" in
start)
    # load modules
    echo "Loading LDD modules"
    modprobe scull
    modprobe faulty
    modprobe hello

    # remove old nodes
    rm -f /dev/scull*
    rm -f /dev/faulty


    # get major numbers
    SCULL_MAJOR=$(cat /proc/devices | awk "\$2==\"scull\" {print \$1}")
    FAULTY_MAJOR=$(cat /proc/devices | awk "\$2==\"faulty\" {print \$1}")

    # create device nodes
    mknod /dev/scull c $SCULL_MAJOR 0
    mknod /dev/scullp c $SCULL_MAJOR 1
    mknod /dev/sculla c $SCULL_MAJOR 2
    mknod /dev/faulty c $FAULTY_MAJOR 0

    ;;
stop)
    echo "Unloading LDD modules"

    # unload modules
    rmmod hello || true
    rmmod faulty || true
    rmmod scull || true

    ;;
restart)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
