name: assignment-test

on:
  push:
    branches:
      - '*'

jobs:
  full-test:
    runs-on: self-hosted

    container:
      image: cuaesd/aesd-autotest:24-assignment7-buildroot
      options: -v /home/jblob/yocto-cache:/yocto-cache -v /home/jblob/yocto-build:/build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install dependencies + locale
        run: |
          apt-get update
          apt-get install -y locales python3-distutils gawk chrpath diffstat lz4 zstd unzip build-essential
          echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
          locale-gen

      - name: Setup builder user and persistent workspace
        run: |
          useradd -m builder || true
          rm -rf build
          ln -s /build build
          mkdir -p build/conf
          chown -R builder:builder build /build /yocto-cache || true

      - name: Setup Yocto cache and persistent TMPDIR
        run: |
          su builder -c "
            if [ ! -f build/conf/local.conf ]; then
              echo 'CONF_VERSION = \"2\"' > build/conf/local.conf
            fi
            
            sed -i '/DL_DIR/d' build/conf/local.conf
            sed -i '/SSTATE_DIR/d' build/conf/local.conf
            sed -i '/TMPDIR/d' build/conf/local.conf
            
            echo 'DL_DIR = \"/yocto-cache/downloads\"' >> build/conf/local.conf
            echo 'SSTATE_DIR = \"/yocto-cache/sstate-cache\"' >> build/conf/local.conf
            echo 'TMPDIR = \"/build/tmp\"' >> build/conf/local.conf
          "

      - name: Fix bblayers.conf (clean)
        run: |
          su builder -c '
            LAYER_PATH=$(realpath meta-aesd)

            # alte kaputte Einträge entfernen
            sed -i "/meta-aesd/d" build/conf/bblayers.conf

            # sauber hinzufügen
            echo "BBLAYERS += \"${LAYER_PATH}\"" >> build/conf/bblayers.conf
          '

      - name: Fix QEMU port in qemuboot.conf
        run: |
          su builder -c "
            CONF_FILE=$(ls build/tmp-glibc/deploy/images/qemuarm64/*.qemuboot.conf | head -n1)

            if [ -f \"$CONF_FILE\" ]; then
              sed -i 's/hostfwd=tcp::2222-:22/hostfwd=tcp::10022-:22/g' $CONF_FILE
            fi
 
      - name: Run full test
        run: |
          su builder -c "
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export HOME=/home/builder

            # QEMU Fix
            export QEMU_PORT=10022
            export QEMU_EXTRA_ARGS='hostfwd=tcp::10022-:22'

            ./full-test.sh
          "
